/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-03-28 11:49:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class questionPosting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hitick</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>Welcome </h2>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/pages/questionPosting.jsp(15,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("/Hitick/save-question-group-mapping-details");
    // /WEB-INF/pages/questionPosting.jsp(15,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    // /WEB-INF/pages/questionPosting.jsp(15,0) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("questionsBean");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<table>\r\n");
          out.write("<tr>\r\n");
          out.write("<td>Question : <td><textarea rows=\"5\" cols=\"60\" name = \"question\" placeholder=\"Type your Question here\"></textarea>\r\n");
          out.write("<td><td><input type=\"hidden\" name = \"refGroupId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${groupId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("<tr><td><td>\r\n");
          out.write("<tr><td>Set time available For Voting (hh:mm) : <td>\r\n");
          out.write("\r\n");
          out.write("<select name=\"hours\">\r\n");
          out.write("\t\t\t\t\t\t<option value=\"0\">- hh -</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"0\">00</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t</select> <select name=\"minutes\">\r\n");
          out.write("\t\t\t\t\t\t<option value=\"0\">- mm -</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"0\">00</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"26\">26</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"27\">27</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"28\">28</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"29\">29</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"31\">31</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"32\">32</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"33\">33</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"34\">34</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"35\">35</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"36\">36</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"37\">37</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"38\">38</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"39\">39</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"40\">40</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"41\">41</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"42\">42</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"43\">43</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"44\">44</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"45\">45</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"46\">46</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"47\">47</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"48\">48</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"49\">49</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"51\">51</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"52\">52</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"53\">53</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"54\">54</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"55\">55</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"56\">56</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"57\">57</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"58\">58</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"59\">59</option>\r\n");
          out.write("\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
          out.write("\t\t\t\t</select>\r\n");
          out.write("\r\n");
          out.write("<tr><td><td><input type=\"submit\" value=\"Submit\">\r\n");
          out.write("</table>\r\n");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }
}
